import { z } from 'zod'

export const ErrorCode = {
  TOPIC_NOT_FOUND: 'TOPIC_NOT_FOUND',
  TOPIC_ALREADY_EXISTS: 'TOPIC_ALREADY_EXISTS',
  SCHEDULE_NOT_FOUND: 'SCHEDULE_NOT_FOUND',
  SCHEDULE_LIMIT_REACHED: 'SCHEDULE_LIMIT_REACHED',
  SCHEDULE_CRON_UNSUPPORTED: 'SCHEDULE_CRON_UNSUPPORTED',
  DELIVERY_TELEGRAM_CHAT_ID_REQUIRED: 'DELIVERY_TELEGRAM_CHAT_ID_REQUIRED',
  DELIVERY_EMAIL_UNAVAILABLE: 'DELIVERY_EMAIL_UNAVAILABLE',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const

export const ErrorCodeSchema = z.enum(ErrorCode).meta({ id: 'ErrorCode' })
export type ErrorCode = z.infer<typeof ErrorCodeSchema>
